<div class="site-info">
  <div class="container">
    <div class="content">
      <div>&copy;<?php print Date('Y');?> JB Foundation. All Rights Reserved.</div>
      <div>Website sponsored by <a href="http://www.whitewalls.in/" target="_blank">
          White Walls Interior Design<span>, Aizawl, Mizoram</span>.</a></div>
    </div>
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="<?php echo $base_url; ?>/js/script.js"></script>