<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-18VZ4SQ4LB"></script>
  <script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
    dataLayer.push(arguments);
  }
  gtag('js', new Date());

  gtag('config', 'G-18VZ4SQ4LB');
  </script>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Animal Rescue in Aizawl, Mizoram : Rescue, Rehabilitate & Educate">
  <title>JB Foundation | A Cause for Paws</title>
  <link href="https://fonts.googleapis.com/css2?family=Catamaran:wght@400;600&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Eczar:wght@400;600&display=swap" rel="stylesheet">
  <link href="<?php echo $base_url; ?>/css/styles.css" rel="stylesheet" />
</head>