 <header class="header">
   <div class="container">
     <div>
       <a class="header__logo" href="<?php echo $base_url; ?>">
         <img src="<?php echo $base_url; ?>/assets/jb-foundation-header.png"
           alt="Jb Foundation, Animal Rescue, Aizawl, Mizoram">
       </a>
     </div>
     <b id="toggle"><span>

       </span></b>
     <div>
       <ul class="main-menu">
         <li><a href="<?php echo $base_url; ?>">Home</a></li>
         <!--
       <li><a href="<?php echo $base_url; ?>/donation">Donate</a></li>
       -->
         <li class="shelter"><a href="<?php echo $base_url; ?>/animal-shelter.php">Animal Shelter</a></li>
         <li><a href="<?php echo $base_url; ?>/contact-us.php">Contact Us</a></li>
       </ul>
     </div>
   </div>
 </header>